name: lyrics818 # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.3.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Generates a lyric video # 79 char long summary
description: |
  lyrics818 generates a lyric video. It expects the lyric file, fonts, background.


grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64

environment:
  LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa-gl:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/xorg:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/
  LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-snaps:
      - go
    build-packages:
      - build-essential
      - gcc
      - libgl1-mesa-dev
      - xorg-dev
      - libc6-dev
    stage-packages:
      - libtinfo5
      - libglu1-mesa
    stage-snaps:
      - ffmpeg
    after:
      - desktop-glib-only

  desktop-glib-only:
    source: .
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin


apps:
  lyrics818:
    command: bin/lyrics818
    plugs:
    - opengl
    - x11
    - desktop
    - wayland
