name: lyrics818 # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.3.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Generates a lyric video # 79 char long summary
description: |
  lyrics818 generates a lyric video in its own format (.l8f).
  It makes two video tracks: one for laptop size and the other for mobile size
  
  It expects the lyric file, fonts, background.

  It's a terminal program.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: go
    source: .


apps:
  lyrics818:
    command: bin/lyrics818

  meta:
    command: bin/meta